### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by kawaxi** [SVelizDonoso/asyrv#1]
Broken link found in Login section.

![2018-10-12 08_51_08-kali2017 1-vm-amd64 balla - vmware workstation](https://user-images.githubusercontent.com/19911604/46873431-2c17a580-cdfc-11e8-8d9d-126b5147730b.png)

**Comment by JakeLBeans** [comment]
Double // by any chance at "html//asyrv" ?

**Comment by kawaxi** [comment]
that was quick....

no, if you remove the / it would still be broken.

**Comment by JakeLBeans** [comment]
Aha I was bored scrolling through some issues to help xD

Double check the file path is correct and that the file has the right file extension.

You could also try going to localhost/var/www/html/ and viewing the index and exploring your way to the file through the in browser file explorer?

**Comment by SVelizDonoso** [comment]
se corrigieron los errores reportados.

muchas gracias por sus aportes.

**Comment by kawaxi** [comment]
tienes que cerrar el ticket desde github para que deje de mostrartelo como abierto.
